language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruits

before_script:
  - psql -c 'create database  fruits;' -U postgres
  - psql -U postgres -d fruits_tests -a -f sql/fruitbasket.sql

services:
  - postgresql